### ISSUE TITLE
Logging 

### ISSUE THREAD

**Issue by Alex-1701** [hosseinmd/react-signalr#10]
Seems like there is no way to disable logging. But microsoft/signalr allow to disable logging. 

Is it possible to add params to Context interface that will forward to microsoft/signalr params?

**Comment by hosseinmd** [comment]
There is nothing about login.
You could use it without access token

**Comment by Alex-1701** [comment]
Not login but logging. I mean debug info in consol.

**Comment by hosseinmd** [comment]
Update react-signalr and add logger to your provider
