### ISSUE TITLE
Use with Streaming (ChannelReader in the Backend)

### ISSUE THREAD

**Issue by Silentapproach** [hosseinmd/react-signalr#11]
Does this npm-package support streaming for signalr? We´re currently in the decision-making whether we to use streaming or events? As far as I can tell from your code, this package only supports events because there is no stream() function in use from the @microsoft/signalr package. 

If you cannot yet support this, are there any plans for the future?

And if you support this, are there any examples that we can learn from? 

Thanks in advance

**Comment by hosseinmd** [comment]
Hi dear.
Yes, I will to support streaming.

**Comment by hosseinmd** [comment]
Because this issue is have opened a long time ago, if it is steel needed from you, I will start to work on it.
