### ISSUE TITLE
20 Console Warnings

### ISSUE THREAD

**Issue by VladRusanov** [hosseinmd/react-signalr#21]
I have 20 warning like 
" Failed to parse source map from '.....\react-signalr\src\webSocket\utils.ts' file: Error: ENOENT: no such file or directory, open '.....\node_modules\react-signalr\src\webSocket\utils.ts' "

**Comment by hosseinmd** [comment]
Fixed v0.2.15

**Comment by VladRusanov** [comment]
I have new problem in the new version
https://github.com/hosseinmd/react-signalr/issues/22

сб, 20 мая 2023 г. в 10:38, Hossein Mohammadi ***@***.***>:
