### ISSUE TITLE
Not getting all messages

### ISSUE THREAD

**Issue by ChillyBots** [hosseinmd/react-signalr#23]
Using your signalR context and hook,  I'm not getting the complete array of messages through, only the first. Our backend provides data in this shape:

`{"type":1,"target":"worksheet_refresh","arguments":[
    "{\"id\":\"\someId",\"actionType\":\"SomeAction\"}", 
    "{\"id\":\"\anotherId",\"actionType\":\"SomeAction\"}", 
]}`

however, the hook returns only the first in the array

**Comment by hosseinmd** [comment]
Parameters apply to hook callback like this
```js
useSignalREffect("event",(arg1,arg2,arg3)=>{},[])
```
