### ISSUE TITLE
Automatic reconnection

### ISSUE THREAD

**Issue by VladRusanov** [hosseinmd/react-signalr#24]
Is it possible to disable automatic reconnection for sockets?

**Comment by hosseinmd** [comment]
Ofcourse, We could. SignalR and Socketio have built-in implementation, But Websocket doesn't have it.

**Comment by VladRusanov** [comment]
> Ofcourse, We could. SignalR and Socketio have built-in implementation, But Websocket doesn't have it.

And how to can do this?

**Comment by hosseinmd** [comment]
Automatic reconnect is enabled for all signalR connections. There is nothing need to do.

**Comment by hosseinmd** [comment]
excu

**Comment by kkfuri** [comment]
I would like to try to help on this one, I'll open a draft PR soon.

**Comment by hosseinmd** [comment]
Thank you @kkfuri. it released v0.2.17
