### ISSUE TITLE
getting multiple hub connection.

### ISSUE THREAD

**Issue by everythinginjs** [hosseinmd/react-signalr#33]
Hello Mr. @hosseinmd tashakor for development and maintenance .

I have used the `SignalRContext` and tried to use `SignalRContext.useSignalREffect` but I see there are two instance of chatHub going on I think one of them is unnecessary!

![Oct-21-2023 16-36-27](https://github.com/hosseinmd/react-signalr/assets/34276557/c9786a28-3572-486f-aac3-fe16dc1f388c)

**Comment by everythinginjs** [comment]
I also get this error in the log which I guess we should check Hubconnection.state if it is Disconnected connect it and if it is Connected disconnected.

<img width="895" alt="Screenshot 2023-10-21 at 5 20 11 pm" src="https://github.com/hosseinmd/react-signalr/assets/34276557/c7306b8b-2fe4-4580-88ad-c8181b9607c4">

**Comment by everythinginjs** [comment]
I found the cause of multiple hub connections it was because of react strict mode.

**Comment by hosseinmd** [comment]
thank you.
