### ISSUE TITLE
Error with @microsoft/signalr 8.0

### ISSUE THREAD

**Issue by fdcastel** [hosseinmd/react-signalr#34]
When using @microsoft/signalr 8 I'm getting this error on build.

```
error TS2322: Type 'signalR.HubConnection | null' is not assignable to type 'import("./src/ts/deucalion-ui/node_modules/@microsoft/signalr/dist/esm/HubConnection").HubConnection | null'.
  Type 'HubConnection' is missing the following properties from type 'HubConnection': _statefulReconnectBufferSize, _sendCloseMessage, _createCloseMessage
```

Related: https://github.com/hosseinmd/react-signalr/issues/28

**Comment by fdcastel** [comment]
@hosseinmd could you please provide a new version with [a similar fix](https://github.com/hosseinmd/react-signalr/issues/28#issuecomment-1712128951) you made in the previous version?

**Comment by aukgit** [comment]
Please upgrade to the latest version @hosseinmd , if you don't support then, please mention it clearly in your docs, as it is misleading and wasting a lot of time.

You should mention clearly which version you support and which you don't.

**Comment by aukgit** [comment]
Thank you @hosseinmd
