### ISSUE TITLE
stop and reconnect method

### ISSUE THREAD

**Issue by fukemy** [hosseinmd/react-signalr#35]
Hi, thanks you for great library, It's work normally after 1 year used in production mode.
Now I have a problem like this:

 When using signalr, when app go to background, the system will kill app so fast, so when open app again, the app re-lauched from initialize state, in this case + calling = I have a trouble in call.
 
  So now, I want to ask the function stop and reconect/connect again when app go to background/active to handle this case. Thanks so much.

**Comment by hosseinmd** [comment]
Hi
I need to clarify "+ calling" and realize what is the meaning. Is it mean you are trying to send an event? For doing something like that, you should wait until connected to the server. I can add something to do it in background.

**Comment by hosseinmd** [comment]
Connection and Reconnection is happening on react useEffect so it depends on react behavior to how reconnecting
