### ISSUE TITLE
Strange behavior with signalr exception and no way to catch the error

### ISSUE THREAD

**Issue by jeffras** [hosseinmd/react-signalr#9]
I am getting an error with signalr where it says the "Method does not exist" but the hub is certainly invoked, and the app is behaving as normal. I cant seem to figure out how to catch and handle this error (seems like a backoff/retry would fix it).

I am hooked up to the onOpen and onReconnect events on the context provider and I make 2 different invoke calls. The first one is a simple "version" call that returns the back end api version. The second starts a timer on the server that sends events every 3 seconds. The first always succeeds, the second always errors out (but works)

![image](https://user-images.githubusercontent.com/1090166/174816839-a0739011-a967-4689-a09b-c261ac20d02f.png)

If I change the client code to 
`if(Context.connection.state === "Connected"){
Context.connection.invoke(...)
}`

Instead of `Context.invoke(...` I do NOT have this issue

Thanks

**Comment by jeffras** [comment]
I am using version "react-signalr": "^0.2.11",

And on the hub I am using net6 where signalr seems to be baked in (no nuget required)

**Comment by hosseinmd** [comment]
Context.invoke is for handling invoke even connection is in another tab, so if you don't share connection between tabs so you could use Context.connection.invoke
